---
language: ruby
dist: jammy

rvm:
  - 2.5
  - 2.6
  - 2.7

env:
  global:
    - PUPPET_VERSION="~> 8.0"
    - PUPPET_GEM_VERSION="~> 8.0"

before_install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - gem --version
  - bundle -v

script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec

deploy:
  provider: puppetforge
  user: akisakye
  password:
    secure: $forge-key
  on:
    tags: true

notifications:
  email: true
