---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
branches:
  only:
    - master
notifications:
  email: true
deploy:
  provider: puppetforge
  user: akisakye
  password:
    secure: "DxL2vG6d47V2KdxSWULsjQuEK0nw5bAKgXbS5TlSQn7rynyx1YkFjnKFZTXRvu0tDaVQDN9nkmd7AaAfaKweHS5LQ1WiiwZzcund9EVuD+HaQpKZKFQRPbT6FUArqohXQNQQMKIQ5mnQadbhKz/dnFP41Y7QA7Aeps4c+gos5AwBshSoxksj5Jb5A1TOnEstj4SBqoL0vQU/3BWemrXWc/AoD64Ta7vQG5lcI6hssyxxES4FO0LE/TBIz0IzFYRFhgYu7SlYvh4V1m4Ow/+eTyvRgXV9sGDlUmzbxddZbicWsTZ8Ky0gVq30a98EicNUQsxz3np2tWzMSBw0DZCH6b9usJsZfPfPoYTwRM0B/lE8iSKxQMNM2NdPiKThjyfd91kY0+jmo6JHvX/EAhpQ9MHbfMCgr2p2trlriSrrfoXf442Nb3CQqX/IKkReRWviK+L8d8P3BT8l8ryXZ+nNTwbvdqe3CIyVeg+5u2ZzN+MgCqGvwdADioZH9HSojUEJNBciuYv1AKhjEaX44TPwTAKE04IzA9bbtU+vbkP8AkHfMc6d//yH3JdDjWwj+kncWtKSd06vgkMUtdkUAQXTWzPXWKF5yGEv21RACocTkDoMRLwVGsMS26PHS46a4AbuDvKir9YQ0XORhMBYBtpXgrf1c9IrnJbCNDumOyiFcZ0="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
