name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs=3 --retry=3

    - name: Lint Puppet manifests
      run: bundle exec rake lint

    - name: Validate Puppet manifests
      run: bundle exec rake validate

    - name: Run spec tests
      run: bundle exec rake spec

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs=3 --retry=3

    - name: Deploy to Puppet Forge
      env:
        PUPPETFORGE_API_KEY: ${{ secrets.PUPPETFORGE_API_KEY }}
      run: |
        bundle exec rake release

    - name: Notify of deployment success
      run: echo "Deployment to Puppet Forge successful."
